module tp2.clases {
    requires com.google.gson;
    requires java.desktop;
    requires javafx.controls;
    requires javafx.graphics;
    requires javafx.media;
    requires org.kordamp.bootstrapfx.core;
    opens tp2.clases to com.google.gson;
    exports tp2.clases;
    exports tp2.clases.controllers.handlers;
    opens tp2.clases.controllers.handlers to com.google.gson;
    exports tp2.clases.view;
    opens tp2.clases.view to com.google.gson;
    exports tp2.clases.model.questions.modes;
    opens tp2.clases.model.questions.modes to com.google.gson;
    exports tp2.clases.model.player.powers;
    opens tp2.clases.model.player.powers to com.google.gson;
    exports tp2.clases.model.player.powers.power_states;
    opens tp2.clases.model.player.powers.power_states to com.google.gson;
    exports tp2.clases.model.player.score.score_states;
    opens tp2.clases.model.player.score.score_states to com.google.gson;
    exports tp2.clases.model.questions;
    opens tp2.clases.model.questions to com.google.gson;
    exports tp2.clases.model.questions.factories;
    opens tp2.clases.model.questions.factories to com.google.gson;
    exports tp2.clases.model.questions.types;
    opens tp2.clases.model.questions.types to com.google.gson;
    exports tp2.clases.model.questions.choice.corrections;
    opens tp2.clases.model.questions.choice.corrections to com.google.gson;
    exports tp2.clases.model.questions.choice.corrections.types;
    opens tp2.clases.model.questions.choice.corrections.types to com.google.gson;
    exports tp2.clases.model.questions.choice;
    opens tp2.clases.model.questions.choice to com.google.gson;
    exports tp2.clases.model.player;
    opens tp2.clases.model.player to com.google.gson;
    exports tp2.clases.model.player.score;
    opens tp2.clases.model.player.score to com.google.gson;
    exports tp2.clases.model;
    opens tp2.clases.model to com.google.gson;
    exports tp2.clases.view.screens;
    opens tp2.clases.view.screens to com.google.gson;
}