@startuml
title: General relationships of the packages used in the model

package questions {
    package choice {}
    package factories {}
    package modes {}
    package types {}
    class Content {}
}

package player {
    package powers {}
    package score {}
    class Player
}

package exceptions {}

package handlers {}

package screens {}

class JsonParser {}

class App {}

player <..> questions: <<access>>
player .> exceptions: <<access>>

questions ..> exceptions: <<access>>

JsonParser ..> questions.choice: <<access>>
JsonParser ..> questions.factories: <<access>>
JsonParser ..> questions.types: <<access>>

handlers <..> screens: <<access>>
handlers ..> player: <<access>>
handlers ..> exceptions: <<access>>

screens ...> player: <<access>>
screens ..> questions: <<access>>
screens .> App: <<uses>>
screens ...> exceptions: <<access>>


@enduml