@startuml
title: A true/false question receives a list of answers and assigns points to those who answered correctly

actor actor
participant ":Question" as question
participant ":TrueOrFalse" as type
participant ":Player" as player
participant ":Score" as score
participant ":Correct" as correction
participant ":Answer" as answer

actor -> question: assignScore(playerAnswers: HashMap<Player, ArrayList<Answer>>)
activate question
question -> question: getNumberOfCorrectAnswers(): int
question -> type: assignScore(playerAnswers, numberOfCorrectAnswers: int)
deactivate question
activate type

loop for each player

    loop for each answer
        type -> answer: getCorrection()
        activate answer
        type <<-- answer: Correct()
        deactivate answer
        type -> player: assignScore(correction: Correct(), newScore: int)
        deactivate type
        activate player
        player -> score: assignScore(correction: Correct(), newScore: int)
        deactivate player
        activate score
        score -> correction: assignScore(newScore: int)
        activate correction
        correction -->> score: score
        deactivate correction
        deactivate score
        note left: totalScore += score
    end loop

end loop
@enduml