@startuml
title: A true/false question receives a list of choices and assigns points to those who answered correctly

actor testCaseOne
participant "question:TrueOrFalse" as question
participant "mode:ClassicMode" as type
participant "aPlayer:Player" as player
participant "score:Score" as score
participant "correction:Correct" as correction

testCaseOne -> question: assignScore(choices)
activate question
loop for each player
question -> question: hasNoIncorrectAnswers(choices)
note left: true
question -> question: getNumberOfCorrectAnswers(choices)
question -> type: assignCorrectScore(player, numberOfCorrectAnswers)
deactivate question
activate type
create correction
type -> correction: new()
type -> player: assignScore(correction, numberOfCorrectAnswers)
deactivate type
activate player
player -> correction: assignScore(score, numberOfCorrectAnswers)
deactivate player
activate correction
correction -> score: addScore(numberOfCorrectAnswers)
deactivate correction
activate score
score -> score: totalScore += numberOfCorrectAnswers

end loop
@enduml