Jugador activa el poder multiplier en
una pregunta de verdadero o falso con penalidad

@startuml Diag rama de Secuencia
title Sequence Diagram: Player uses Multiplier on True or False with penalty question


hide footbox

participant "testCase02" as actor
participant "aPlayer:Player" as player
participant "question:TrueOrFalse" as question
participant "power:Multiplier" as power
participant "state:Inactive" as state




actor -> player: useMultiplier(2)
note left
    Misma secuencia para el guardado de respuestas 
    que en "SecuenceDiagramCaseOfUseFivePartOne"
end note
activate player
player -> power: getMultiplier(2)
activate power
power -> power: isInactive()
note left: true
power -> state: activate()
activate state

player -> player: disablePowers()
player -> power: disableMultipliers()
deactivate player
loop for each Multiplier
power -> state: deactivate()
state -> state: deactivate()
end loop
deactivate power
deactivate state
actor -> question: assignScore(aPlayer, choices)
note right
    Misma secuencia para la asignacion de puntos
    que en "SecuenceDiagramCaseOfUseFivePartTwo"
end note


@enduml